name: sea-salon
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password # change this
      MYSQL_DATABASE: sea_salon

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_NAME: sea_salon
      DB_USER: root
      DB_PASS: password # change this
      DB_HOST: db
      MAX_RETRIES: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    