name: sea-salon
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sea_salon
    
    # Delete later (Temporary)
    deploy:
      resources:
        limits:
          memory: 1G